name: Simple Local

on: 
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Diga oi
        run: echo "Hello World!"

      - name: Instalar dependências
        run: npm install

      - name: Executar app
        run: node app.js

